name: auth_flow_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  supabase_flutter: ^2.12.0
  flutter_dotenv: ^6.0.0
  pinput: ^6.0.2
  google_sign_in: ^7.2.0
  shared_preferences: ^2.5.5



  # Dependency Injection
  get_it: ^9.2.1

  # Functional Programming & Error Handling
  dartz: ^0.10.1

  # UI Components
  cupertino_icons: ^1.0.8

  # Image Picker
  image_picker: ^1.2.1

  # HTTP
  http: ^1.6.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env